package ca.gosecure.cspauditor.gui.generator;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Collection;
import java.util.Vector;

public class CspGeneratorPanel {
    private JButton analyseButton;
    private JComboBox comboBox1;
    private JPanel rootPanel;
    private JButton refreshButton;
    private JTabbedPane resultTabbedPane;
    private JPanel configurationPanel;
    private JPanel inlineScriptPanel;
    private JTable resourcesTable;
    private JPanel resourcePanel;
    private JTable inlinesTable;
    private JPanel inlinePanel;

    DefaultTableModel tableResourcesModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };
    DefaultTableModel tableInlinesModel = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };


    private CspGeneratorPanelController controller;
    //private CspGeneratorPanelUiProvider uiProvider;

    public CspGeneratorPanel(CspGeneratorPanelController controller) {
        this.controller = controller;
        //this.uiProvider = uiProvider;

        init();
    }

    private void init() {

        //Resources table
        tableResourcesModel.addColumn("Request");
        tableResourcesModel.addColumn("Type");
        resourcesTable.setModel(tableResourcesModel);

        resourcesTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            int viewRow = resourcesTable.getSelectedRow();

            Vector values = (Vector) tableResourcesModel.getDataVector().get(viewRow);
            selectResourceItem((String) values.get(0));
        });

        //Inlines table

        tableInlinesModel.addColumn("Request");
        tableInlinesModel.addColumn("Code");
        inlinesTable.setModel(tableInlinesModel);

        inlinesTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            int viewRow = inlinesTable.getSelectedRow();

            Vector values = (Vector) tableInlinesModel.getDataVector().get(viewRow);
            selectInlineItem((String) values.get(0));
        });

        //Analyze

        analyseButton.addActionListener((ActionEvent e) -> {
            String value = (String) comboBox1.getSelectedItem();
            if (value != null)
                controller.analyzeDomain(value);
        });


        //Refresh button
        this.refreshButton.setText("\u21BB");
        refreshButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                controller.refreshDomains();
            }
        });
    }

    public JPanel getRootPanel() {
        return rootPanel;
    }

    ////Domains

    public void clearDomains() {
        comboBox1.removeAll();
    }

    public void addDomains(Collection<String> domains) {
        for (String domain : domains) {
            comboBox1.addItem(domain);
        }
    }

    ////Configurations

    public void setConfiguration(Component configuration) {
        configurationPanel.removeAll();
        configurationPanel.add(configuration);
    }

    ////Resources

    public void clearResources() {
        tableResourcesModel.setRowCount(0);
    }

    public void addResource(String url, String type) {
        tableResourcesModel.addRow(new String[]{url, type});
    }

    public void selectResourceItem(String path) {
        controller.selectResource(path);
    }

    public void setResourceItem(Component resource) {
        resourcePanel.removeAll();
        resourcePanel.add(resource);
    }

    ////Inlines scripts

    public void clearInlineScript() {
        tableInlinesModel.setRowCount(0);
    }

    public void addInlineScript(String urlString, String line) {
        tableInlinesModel.addRow(new String[]{urlString, line});
    }

    public void selectInlineItem(String path) {
        controller.selectInline(path);
    }

    public void setInlineItem(Component resource) {
        inlinePanel.removeAll();
        inlinePanel.add(resource);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        rootPanel.add(panel1, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel2.setEnabled(true);
        panel1.add(panel2, BorderLayout.NORTH);
        comboBox1 = new JComboBox();
        panel2.add(comboBox1, BorderLayout.CENTER);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.add(panel3, BorderLayout.EAST);
        refreshButton = new JButton();
        refreshButton.setText("Refresh");
        panel3.add(refreshButton);
        analyseButton = new JButton();
        analyseButton.setHideActionText(true);
        analyseButton.setText("Analyze");
        panel3.add(analyseButton);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        panel1.add(panel4, BorderLayout.CENTER);
        resultTabbedPane = new JTabbedPane();
        resultTabbedPane.setTabLayoutPolicy(0);
        panel4.add(resultTabbedPane, BorderLayout.CENTER);
        configurationPanel = new JPanel();
        configurationPanel.setLayout(new BorderLayout(0, 0));
        resultTabbedPane.addTab("Configuration", configurationPanel);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        resultTabbedPane.addTab("External Resources", panel5);
        final JSplitPane splitPane1 = new JSplitPane();
        splitPane1.setOrientation(0);
        panel5.add(splitPane1, BorderLayout.CENTER);
        resourcePanel = new JPanel();
        resourcePanel.setLayout(new BorderLayout(0, 0));
        splitPane1.setRightComponent(resourcePanel);
        final JScrollPane scrollPane1 = new JScrollPane();
        splitPane1.setLeftComponent(scrollPane1);
        resourcesTable = new JTable();
        scrollPane1.setViewportView(resourcesTable);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        resultTabbedPane.addTab("Inline Scripts", panel6);
        final JSplitPane splitPane2 = new JSplitPane();
        splitPane2.setOrientation(0);
        panel6.add(splitPane2, BorderLayout.CENTER);
        final JScrollPane scrollPane2 = new JScrollPane();
        splitPane2.setLeftComponent(scrollPane2);
        inlinesTable = new JTable();
        scrollPane2.setViewportView(inlinesTable);
        inlinePanel = new JPanel();
        inlinePanel.setLayout(new BorderLayout(0, 0));
        splitPane2.setRightComponent(inlinePanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
